#!/bin/sh
blockMesh

#interFoam
decomposePar

mpirun -np 4 interFoam -noFunctionObjects -parallel

reconstructPar

interFoam -postProcess
#------------------------------------------------------------------------------
